repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.3.1
          - pydocstyle==4.0.0
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
